### PR TITLE
feat: add option to fail builds on error

### PR DESCRIPTION
**Pull request by raphlcx**
### Description 描述

When there are errors from stylelint, add an option to fail builds.

Currently, stylelint errors are emiited, but they do not have the capability to fail builds. It would be nice to be able to fail builds, similar to what [`stylelint-webpack-plugin`](https://github.com/webpack-contrib/stylelint-webpack-plugin#failonerror) provides.

### Linked Issues 关联的 Issues

https://github.com/nuxt-modules/stylelint/issues/89

### Additional context 额外上下文

Might need help to refine the Chinese translation if it can be better.

### CODE REVIEW

**Comment by raphlcx** [comment]
cc: @ModyQyW

**Comment by ModyQyW** [comment]
We don't need to set errored manually since Stylelint already did this. If we want to fail builds, we need to use `context.error`.

**Comment by raphlcx** [comment]
Thanks for the review.

Should we set context error if `failOnError` is true instead?

https://github.com/ModyQyW/vite-plugin-stylelint/blob/dd5cc45f768848580be8d9e7fef65ff61441072c/src/utils.ts#L112

**Comment by ModyQyW** [comment]
In `log` and `lintFiles` functions, context will be used when passed.

The problem is, passing context to `lintFiles` called in Chokidar onChange event will cause an error and quit Vite process when we enable `chokidar` option, which is not expected.

https://github.com/ModyQyW/vite-plugin-stylelint/blob/v5.1.1/src/index.ts#L78-L98

**Comment by raphlcx** [comment]
If we set both `chokidar: true` and `failOnError: true`, is it expected to quit Vite process on errors? Or it should only fail but not quit the process?

Once we introduce the `failOnError` flag, if the flag is false, just by enabling chokidar should not quit Vite process on errors.

I'm imagining the following implementation:

```js
if (textType === 'error' && failOnError /* flag is passed into the log function */) {
  context.error(text);
}
```

**Comment by ModyQyW** [comment]
I apologize that I may not have expressed my opinion correctly and completely before. And sorry I am late in response.

Normally, enabling `lintInWorker` would only show errors and warnings in the console, but otherwise in the console and the browser.

Now, with `chokidar` enabled and `lintInWorker` disabled, I can't pass the context to the function (see https://github.com/ModyQyW/vite-plugin-stylelint/blob/v5.1.1/src/index.ts#L78-L98 comments) because it causes an error and just quits the Vite process. This leads to the problem mentioned in https://github.com/nuxt-modules/stylelint/issues/89, where the plugin only displays error and warning messages in the console, not in the browser.

I don't think adding an option called `failOnError` solves this problem. To fix this, we need to pass the context and avoid the error.

I think we only need to quit the process if the `lintOnStart` option is enabled and an error is checked, which would request the user to deal with the error that exists first to avoid caching issues ⬇️, which is exactly what this plugin currently behaves like.

image

**Comment by ModyQyW** [comment]
@raphlcx Hi. I wonder if you are working on this still?

**Comment by raphlcx** [comment]
@ModyQyW not at the moment. I might take a peek again when I have some time later, if it's not resolved yet.

For now, we can close this PR if the implementation isn't in the right direction.

Also, thank you for the comprehensive explaination in your previous comment!

**Comment by ModyQyW** [comment]
> @ModyQyW not at the moment. I might take a peek again when I have some time later, if it's not resolved yet.
> 
> For now, we can close this PR if the implementation isn't in the right direction.
> 
> Also, thank you for the comprehensive explaination in your previous comment!

@raphlcx Hi. Thanks for your reply and efforts! I have opened a new issue https://github.com/ModyQyW/vite-plugin-stylelint/issues/51 and I am closing this PR.

**Pull request closed without merging**
