### PR TITLE
feat!: remove chokidar and use handleHotUpdate to handle deep imports

### PR DESCRIPTION
**Pull request by HawtinZeng**
### Linked Issues 关联的 Issues
#51

### Additional context 额外上下文
Can't lint imported scss files while hot module replacement is triggered.
I need reviewers focus on the solution is suitable or not, so I can write some tests to cover more cases.

## Summary by CodeRabbit

- **New Features**
	- Introduced a GitHub Actions workflow for Playwright tests in Vue examples.
	- Added Playwright test configuration for parallel execution across major browsers in Vue examples.
	- New styling rules for Vue.js application components via `testStyleImport.scss`.
	- Added test cases for Vite plugin configurations in Vue examples.

- **Bug Fixes**
	- Updated `.gitignore` files to include new exclusions and remove outdated ones.
	- Modified `stylelint` rules in Vue examples for improved code quality.

- **Chores**
	- Adjustments to project configuration files for better development experience.

- **Refactor**
	- Streamlined logic in utility functions and hooks for clarity and performance.

- **Style**
	- Formatting adjustments in React examples for consistency.

- **Documentation**
	- No visible changes to end-users.

### CODE REVIEW

**Comment by HawtinZeng** [comment]
The lint process may take place in both transform and handleHotUpdate hook.

**Comment by ModyQyW** [comment]
I think you are trying to remove chokidar and use handleHotUpdate to lint imported scss files. Am I right? That is a good idea, but the issue title really confused me.

**Comment by HawtinZeng** [comment]
Yes, It looks confusing.I changed the PR title.

**Comment by ModyQyW** [comment]
I think it is a breaking change feat since we can remove chokidar and chokidar-related options. Is it true?

**Comment by HawtinZeng** [comment]
Yes, we should write some tests.

**Comment by ModyQyW** [comment]
You can follow https://github.com/nuxt-modules/stylelint/issues/89#issuecomment-1592027011 to get some bounty.

**Comment by HawtinZeng** [comment]
OK

**Comment by HawtinZeng** [comment]
I will check the code later.

**Comment by ModyQyW** [comment]
Hi @HawtinZeng .I'm sorry to bother you. Are you still willing to move forward with this PR?

**Comment by HawtinZeng** [comment]
Yes, I pushed the hmr lint feat, and I will continue to write some test cases.

**Comment by HawtinZeng** [comment]
hi, i think you don't want to merge this pr, so i will close it. If you have any decision, please let me know.

**Comment by ModyQyW** [comment]
I left 5 reviews but got no responses.

**Comment by HawtinZeng** [comment]
I thought these reviews is auto generated by a robot.

**Comment by HawtinZeng** [comment]
Hi, I have changed some code, can u review these changes.

**Comment by ModyQyW** [comment]
> Hi, I have changed some code, can u review these changes.

Sorry, but I don't see any code changes for reviews.

**Comment by HawtinZeng** [comment]
> > Hi, I have changed some code, can u review these changes.
> 
> Sorry, but I don't see any code changes for reviews.

Maybe because I forcely amend the last commit

**Pull request closed without merging**
